


all: hcmv hepc

hcmv:
	python3  omni2treeview.py  -n demo/hcmv_tree.nwk -m demo/hcmv_meta.csv -c demo/hcmv_five_letter_taxon.tsv  -t template_v5.html -l hcmv  -o  demo/omni2treeview_hcmv
hepc:
	python3  omni2treeview.py  -n demo/HepC_tree.nwk -m demo/HepC_metadata_merged.csv  -t template_v5.html -l HepC  -o  demo/omni2treeview_HepC